# Generated by Django 3.2.7 on 2021-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogifyuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
