# Generated by Django 3.2.7 on 2021-09-11 10:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blogifyuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogifyuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_profile_pic),
        ),
    ]
