# Generated by Django 3.2.7 on 2021-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_created',
        ),
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
