# Generated by Django 3.2.7 on 2021-09-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('liked_article', 'liked_by'), name='like_once'),
        ),
    ]
